In [22]:
import pandas as pd
from pathlib import Path

In [35]:

def display_average(averages, stds, decimals=2):
    """
    Combine averages and standard deviations into the format:
    mean (std).

    Parameters
    ----------
    averages : pandas.DataFrame
        Mean values.

    stds : pandas.DataFrame
        Standard deviation values.

    decimals : int, default=3
        Number of decimal places.

    Returns
    -------
    pandas.DataFrame
        Formatted table.
    """
    result = averages.copy().astype(str)

    for col in averages.columns:
        result[col] = [
            f"{avg:.{decimals}f} ({sd:.{decimals}f})"
            for avg, sd in zip(
                averages[col],
                stds[col],
            )
        ]

    return result



def read_simulation(path, methods, metrics):
    """
    Read simulation results and summarize them as mean (std).

    Parameters
    ----------
    path : str
        Directory containing the result files.

    methods : list of str
        Method names.

    metrics : list of str
        Metrics to summarize.

    Returns
    -------
    pandas.DataFrame
        Table with entries formatted as mean (std).
    """
    path = Path(path)

    averages = pd.DataFrame(index=methods, columns=metrics, dtype=float)
    stds = pd.DataFrame(index=methods, columns=metrics, dtype=float)

    for method in methods:

        file_path = path / f"{method}.txt"

        if not file_path.exists():
            raise FileNotFoundError(
                f"File not found:\n{file_path}"
            )

        results = pd.read_csv(file_path)
        results = results.loc[:, metrics]
        averages.loc[method] = results.mean()
        stds.loc[method] = results.std()
    return display_average(averages=averages, stds=stds)

### Synthetic Dataset 1

In [ ]:
path = '../synthetic_application/results/synthetic_1'
methods= ['IFCM', 'KFCM-IV', 'IFDK', 'IKFDK-O', 'IKFDK-K']
metrics = ['ARI', 'ARI_col', 'CARI']
X =read_simulation(path=path, methods=methods, metrics=metrics)
X

                 ARI      ARI_col         CARI
IFCM     0.38 (0.07)  0.44 (0.11)  0.31 (0.06)
KFCM-IV  0.38 (0.08)  0.88 (0.06)  0.50 (0.06)
IFDK     0.73 (0.18)  0.58 (0.14)  0.57 (0.17)
IKFDK-O  0.95 (0.13)  0.66 (0.23)  0.74 (0.19)
IKFDK-K  1.00 (0.00)  1.00 (0.00)  1.00 (0.00)

### Synthetic Dataset 2

In [ ]:
path = '../synthetic_application/results/synthetic_2'
methods= ['IFCM', 'KFCM-IV', 'IFDK', 'IKFDK-O', 'IKFDK-K']
metrics = ['ARI', 'ARI_col', 'CARI']
X =read_simulation(path=path, methods=methods, metrics=metrics)
X

                 ARI      ARI_col         CARI
IFCM     0.35 (0.07)  0.52 (0.11)  0.33 (0.07)
KFCM-IV  0.35 (0.08)  0.52 (0.11)  0.33 (0.06)
IFDK     0.60 (0.09)  0.72 (0.11)  0.56 (0.09)
IKFDK-O  0.77 (0.12)  0.69 (0.14)  0.65 (0.10)
IKFDK-K  0.94 (0.14)  1.00 (0.01)  0.96 (0.10)